services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports: 
      - "8000:8000"
    image: fastapi_app
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/mydatabase
    volumes:
      - .:/app  # Bind Mount
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: # name volume  